# Generated by Django 5.2.9 on 2025-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paper_review_comment_paper_review_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('KEYNOTE', 'Keynote'), ('PRESENTATION', 'Paper Presentation'), ('WORKSHOP', 'Workshop'), ('PANEL', 'Panel Discussion')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hall', models.CharField(blank=True, max_length=100)),
                ('speaker', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
