# Generated by Django 5.2.9 on 2025-12-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conferencesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_order', models.PositiveIntegerField(default=1)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_slot', to='core.paper')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='core.conferencesession')),
            ],
        ),
    ]
